// USER
export const TOGGLE_LOGGED_IN = 'TOGGLE_LOGGED_IN';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const SET_USER_ERROR = 'SET_USER_ERROR';

// SEARCH
export const SET_SOURCE = 'SET_SOURCE';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_JOURNEY_DATE = 'SET_JOURNEY_DATE';
export const SET_RESULTS = 'SET_RESULTS';

// BUSES
export const SET_COURSES = 'SET_COURSES';
export const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE';

// EVALUATIONS
export const SET_EVALUATIONS = 'SET_EVALUATIONS';
export const SET_CURRENT_EVALUATION = 'SET_CURRENT_EVALUATION';

// BOOKING
export const SET_BOOKING_SEATS = 'SET_BOOKING SEATS';
export const SET_PASSENGERS_DETAIL = 'SET_PASSENGERS_DETAIL';

// LOADING
export const SET_LOADING = 'SET_LOADING';
